apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: datacollector-deploy-to-test
spec:
  timeout: 1h0m0s
  pipelineRef:
    name: microservice-deploy-pipeline
  params:
    - name: git-url
      value: "https://github.com/Andrej220/HAM.git"
    - name: gitops-url
      value: "git@github.com:Andrej220/HAM-gitops.git"
    - name: serviceName
      value: "datacollector"
    - name: imageName
      value: "local-registry.registry.svc.cluster.local:5000/datacollector:latest"
    - name: targetEnv
      value: "test"
    - name: servicePort
      value: "8081"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        metadata:
          name: "pipeline-workspace"
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
    - name: gitops-data
      volumeClaimTemplate:
        metadata:
          name: "pipeline-gitops-workspace"
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

